- Account/Api.cs
- Account/CustomField.cs
- Account/IApi.cs
- Api.cs
- Contact/Company.cs
- Contact/Contact.cs
- Contact/IApi.cs
- Event/Api.cs
- Event/Attendee.cs
- Event/Event.cs
- Event/IApi.cs
- Event/Registration.cs
- Extensions/Extension.cs
- Extensions/IExtension.cs
- Extensions/Setup/SetupRequest.cs
- Extensions/Unsetup/UnsetupRequest.cs
- Invoice/Api.cs
- Invoice/IApi.cs
- Invoice/Invoice.cs
- Invoice/InvoicePayment.cs
- Json/Converters/ResponseConverter.cs
- ResultOrError.cs
- Test/IApi.cs
- Utils.cs
- Venue/Api.cs
- Venue/IApi.cs
- Venue/RatePlan.cs
- Venue/Room.cs
1. Added two APIs getAttendeeListForAccount and getRegistrationListForAccount.
2. Changed the datatype of CustomField class's FileType field.
3. Added few fields in Attendee and Registration Model.
4. Modified the constuctor of Extension.cs to use correct parameter.
5. Removed the redundance qualifiers from the Api Methods.
6. Removed the unused namespaces from all the classes.
7. Changed the Public properties name to start with an uppercase letter.
8. Added parameters information in the Method documentation.
9. Used expression bodied properties in ResponseConvertor.
10. Removed null assignment from the ResultOrErrors Public variables, as string's default value is null.
11. Changed the Utils class to static instead of sealed.
> Latest API changes and model related changes

- Event/Event.cs
Added modified date in Event model.
> Changes in Event Model

- Account/EmailLog.cs
- Api.cs
- Event/Attendee.cs
- Extensions/Extension.cs
- Extensions/IExtension.cs
- IApi.cs
[AE-480]: 1. Event Attendee can have contactId as null, so changed the datatype from int to nullable int (int?).
2. Removed the parameterized constructor from API and Extension class and added the empty constructor
3. Made the properties public by adding those in interface.
4. Removed the Initialize methods from both API and Extension classes.
> Changes to resolve the Dependency issue

- Contact/Contact.cs
Added ExternalId property in Contact model to get/create/update the contact using external id.
> Changes in Contact Model

- Contact/Contact.cs
Added two new properties **Companies** and **CompanyData** to **Contact** model.
> Ae 531 contact model changes

- Invoice/Item.cs
- Added RefType enum for Invoice Item
- Invoice Item string RefType to enum RefType
> AE-647 iVvy SDK Change for iVvy RefType

- Invoice/Api.cs
- Invoice/IApi.cs
- Changed Invoice filter parameter to support other types than string
> AE-513  - Changed Invoice filter parameter to support other types than string

- Event/InvitedContact.cs
-  Make RegistrationId Nullable
> - Make RegistrationId Nullable

- Contact/Contact.cs
Modified EmailStatus and SmsStatus to nullable
> - Modified EmailStatus and SmsStatus to nullable

- Contact/Api.cs
- Contact/Company.cs
- Contact/IApi.cs
- Added AddOrUpdateCompanyAsync method with post data
- Added modified date to Company model
> Added Company API's and Company Model change

- Event/Attendee.cs
- Changed AttendedDatetime && SessionAttendedTimestamp to Nullable
> -  Changed AttendedDatetime && SessionAttendedTimestamp to Nullable

- Account/Api.cs
- Account/CostCenter.cs
- Account/IApi.cs
Added an endpoint for retrieving all cost centers in an account.
> Added GetCostCenterList action.

- Venue/Booking.cs
- Venue/Bookings/Session.cs
Added all needed members of the session property.
> Added sessions to Booking.

- CRM/Api.cs
- CRM/IApi.cs
- CRM/LeadStages.cs
- CRM/LeadTypes.cs
This apis provides list of opportunity stages and lead types list.
> Added new APIs Opportunity lead type list and Lead stage list for CRM.

- Contact/Agent.cs
* Id property in the Agent object change to an integer.
> * Agent object update.

- Venue/Bookings/RoomReservationRoom.cs
Added the property "overrideBlockCapacity" in  the RoomReservationRoom.cs file. which is a boolean which if set to true, which will allow you to push in more reservations than the number on the block.
> Added the property "overrideBlockCapacity" in  the RoomReservationRoom class.

- src/ApiCallDetails.cs
- src/ApiClient.cs
- src/Venue/Bookings/CostCentreCommission.cs
- src/Venue/Bookings/Product.cs
Expose the CostCenterId from the Booking.Product class and ensure that it is spelled correctly.
> CostCenterId changes

- src/Venue/ApiClient.cs
- src/Venue/Bookings/SpaceBlockout.cs
- src/Venue/IApiClient.cs
API extended with SpaceBlockout functions.
> Extend api with blockout functions

- src/Venue/ApiClient.cs
- src/Venue/IApiClient.cs
Id added for blockouts update in AddOrUpdateSpaceBlockout function and pagination parameters added in GetVenueSpaceBlockoutList.
> Blockout api functions modifications.

- src/Crm/Lead.cs
Lead property CustomFields type changed from CustomField to List<CustomField>.
> Lead property CustomFields fix.

- src/Contact/Company.cs
IsAgent property added to a company data.
> IsAgent field added to a company data.

- src/Contact/Contact.cs
- src/Ivvy.API.csproj
- src/Venue/Bookings/AccommodationRoomOption.cs
- src/Venue/Bookings/Package.cs
- tests/Ivvy.API.UnitTests.csproj
New properties added to Package, Contact and AccommodationRoomOption data and Newtonsoft Json package updated.
> New properties added to Package, Contact and AccommodationRoomOption data.

- src/Venue/Booking.cs
- src/Venue/Bookings/ServiceFee.cs
- src/Venue/Bookings/TaxDetail.cs
ServiceFees data included in Booking object.
> ServiceFees data included in Booking object.
